### ISSUE TITLE
略加改动使得可回车输入国罗原文

### ISSUE THREAD

**Issue by arsenali** [Chingyat/rime-romatzyh#1]
原版上屏码中的字与字之间会自动加上空格，但对于国罗来说其实用不着，我改动了一下，使得上屏码连续显示无空格，词与词之间需要空格时用分号输入，需要分词时用分号'，点回车严格按照显示的上屏码上屏，点空格上屏选汉字，这样就把它改造成国罗拼音和汉字的二重输入法
https://github.com/arsenali/rime/blob/master/romatzyh.custom.yaml

还有就是用v来替代轻声符号，赵元任是说用句号.，但效果并不好，还是用v吧
還有就是加入了一些簡拼規則，比如ch-q, sh-x, iann-ien, iuann-von，減少單字編碼長度

另外目前方案無法實現簡拼，原版地球拼音和許氏注音是可以實現簡拼的，不知道國羅要怎麼設置

**Comment by fuzy112** [comment]
已添加簡拼功能。
