### ISSUE TITLE
欸ㄝê(eh1)的处理有点问题

### ISSUE THREAD

**Issue by arsenali** [Chingyat/rime-romatzyh#2]
地球拼音码表（terra_pinyin.dict.yaml）中，
欸	eh1
这个音在国语罗马字方案中没有做处理，现在用eh打不出来这个字，不过也不知道赵元任先生对于这个音有没有做出过规定呢？ㄝê(eh)这个音节的五个声调（ê̄ếê̌ềê）的国罗转写方案有过正式的规定吗？我还需要先到国罗群里讨论一下先呢，我目前还没有找到这个统一的规定的呢

**Comment by fuzy112** [comment]
從網上能找到的資料來看，ㄝ應該寫作è （è, èr, èè, èh）。
- - - - -
[http://www.chinaknowledge.de/Literature/Script/gwoyeu.html](http://www.chinaknowledge.de/Literature/Script/gwoyeu.html)
[http://cidian.eduu.com/fl/3](http://cidian.eduu.com/fl/3)
[http://www.pkucn.com/thread-193262-1-1.html](http://www.pkucn.com/thread-193262-1-1.html)

**Comment by arsenali** [comment]
看来赵元任的方案是把ㄝ的四种变化和ㄜ做一样来处理，只是把e写作了è（为什么呢，我觉得应该是ê才对的），但是这样一来这就不是26键罗马化方案了的，如果想把它完善成为26键以内的方案，必需进行转写的，目前看来我能想到的最佳方案就是把ㄝ和ㄜ合并了，然后轻声还是用v，因为ㄝ单写的汉字只有两个“誒欸”，把它们合并到ㄜ中相当于是用到了模糊音，这样的话ê̄ếê̌ềê就是e, er, ee, eh, ev了

**Comment by arsenali** [comment]
我觉得国罗方案每个音节其实应该有六种写法才算完美，无声调、一声、二声、三声、四声、轻声，六种写法各不相同，赵元任的方案把无声调和轻声都等同于一声，这其实是造成了编码的低效性的，我现在是把轻声区别开来，使得一声和轻声可以有所不同的

不过说起来，目前的方案还是不够完美，虚母的轻声有错，因为目前的轻声是保持和一声一致的，但是像ㄓㄔㄕㄖㄗㄟㄙ这7个虚母它们的韵母是i-不是i，汉语拼音把它们混淆了，结果是它们的轻声就没有改，比如像“汉子”的“子”是tzi而不是tzy，不知道老大您有时间的时候能不能改一下下的

**Comment by fuzy112** [comment]
已改。
