### ISSUE TITLE
请教一下尖音处理问题

### ISSUE THREAD

**Issue by arsenali** [Chingyat/rime-romatzyh#3]
我制作了个带调尖音词库terra_pinyin.zianyin.dict.yaml，通过terra_pinyin.extended.dict.yaml导入成功，通过定制许氏和国罗方案实现正常输入，但是用国罗输入尖音的时候有点小问题，tz/ts+üe/üan/ün的时候会有问题：
**絕	zve2**
zyue可以
![zue2](https://cloud.githubusercontent.com/assets/27876448/26035224/a22f56f6-38fb-11e7-8892-fef349b145f4.png)
tzyue不行
![zue2_](https://cloud.githubusercontent.com/assets/27876448/26035245/061ead74-38fc-11e7-8751-7768893b6f81.png)

**全	cvan2**
cyuan可以
![cuan2](https://cloud.githubusercontent.com/assets/27876448/26035266/5454a048-38fc-11e7-82b8-b45a981ff04f.png)
tsyuan不行
![cuan2_](https://cloud.githubusercontent.com/assets/27876448/26035273/6c0e01d4-38fc-11e7-922e-2c899943afef.png)

**俊	zvn4**
ziunn可以
![zun4](https://cloud.githubusercontent.com/assets/27876448/26035318/dae182a2-38fc-11e7-9cfd-435d7b6d10c3.png)
tziunn不行
![zun_](https://cloud.githubusercontent.com/assets/27876448/26035321/e30ff008-38fc-11e7-97ce-08ea1e1fdc92.png)

s+üe/üan/ün不存在这个问题，像seue雪、syuan旋、seuan选、syun寻，都正常
不知道是怎么回事呢？
尖音码表中用v代表ü（和地球拼音码表保持一致），以zii, cii, sii编码积、七、夕。可从我的github下载
https://github.com/arsenali/rime

非常感谢你的方案~

**Comment by arsenali** [comment]
已找到方法，
    - xform/\<z([aeiouyY])/tz$1/
    - xform/\<c([aeiouyY])/ts$1/
改为
    - xform/\<z([aeiouvyY])/tz$1/
    - xform/\<c([aeiouvyY])/ts$1/
即可

谢谢！

**Comment by Chingyat** [comment]
??

________________________________
