### ISSUE TITLE
題外話…

### ISSUE THREAD

**Issue by chowhoyin** [Chingyat/rime-romatzyh#7]
大佬有興趣做粵羅嗎？😳表示想用……

**Comment by fuzy112** [comment]
是 [这个](https://zh.wikipedia.org/zh-hans/%E7%B2%A4%E8%AF%AD%E7%BD%97%E9%A9%AC%E5%AD%97) 吗？
周末我试着做一下。

**Comment by chowhoyin** [comment]
是的，非常感謝！

**Comment by fuzy112** [comment]
欢迎试用粤语罗马字输入方案 https://github.com/Chingyat/rime-yutlo 。基于 https://github.com/rime/rime-cantonese 带声调粤拼词典制作，受词典限制，不分精照。

如果有任何问题，欢迎提 issue。

**Comment by chowhoyin** [comment]
感謝啊！！！試用中，暫時沒發什麼什麼問題~
